apiVersion: apps/v1
kind: Deployment
metadata:
  name: mmux
  labels:
    app: mmux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmux
  template:
    metadata:
      labels:
        app: mmux
    spec:
      containers:
        - name: mmux
          image: ghcr.io/mahyar-mesbah/website:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
          resources:
            requests:
              cpu: "20m"
              memory: "32Mi"
            limits:
              memory: "128Mi"
